package Penjualan_Motor_Java;

import java.util.Date;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;

public class TugasAkhirPBO extends javax.swing.JFrame {

    private DecimalFormat decimalFormat = new DecimalFormat("Rp###,###,###");
    private boolean isResultDisplayed = false;

    /**
     * Creates new form NewJFrame
     */
    public TugasAkhirPBO() {
        initComponents();
        nonaktif();

        combo_merk.addItem("PILIH");
        combo_merk.addItem("HONDA");
        combo_merk.addItem("YAMAHA");
        combo_merk.addItem("SUZUKI");
        combo_merk.addItem("KAWASAKI");

        combo_byr.addItem("PILIH");
        combo_byr.addItem("TUNAI");
        combo_byr.addItem("KREDIT");

    }

    void clear() {
        combo_merk.setSelectedItem("PILIH");
        combo_byr.setSelectedItem("PILIH");
        tNama.setText("");
        tHarga.setText("");
        tDiskon.setText("");
        tTotbay.setText("");
        buttonGroup1.clearSelection();
    }

    void aktif() {
        tNama.setEnabled(true);
        combo_merk.setEnabled(true);
        rb_man.setEnabled(true);
        rb_sprt.setEnabled(true);
        rb_mtc.setEnabled(true);
        combo_byr.setEnabled(true);
        btn_hitung.setEnabled(true);
    }

    void nonaktif() {
        tNama.setEnabled(true);
        combo_merk.setEnabled(false);
        rb_man.setEnabled(false);
        rb_sprt.setEnabled(false);
        rb_mtc.setEnabled(false);
        tHarga.setEnabled(false);
        combo_byr.setEnabled(false);
        tDiskon.setEnabled(false);
        tTotbay.setEnabled(false);
        btn_hitung.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combo_merk = new javax.swing.JComboBox<>();
        rb_man = new javax.swing.JRadioButton();
        rb_sprt = new javax.swing.JRadioButton();
        rb_mtc = new javax.swing.JRadioButton();
        tHarga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tDiskon = new javax.swing.JTextField();
        tTotbay = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        combo_byr = new javax.swing.JComboBox<>();
        btn_hitung = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        button_print = new javax.swing.JButton();
        button_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PENJUALAN MOTOR");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("NAMA PEMBELI");

        jPanel2.setBackground(new java.awt.Color(51, 255, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("DATA MOTOR");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("MERK MOTOR");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("JENIS MOTOR");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("HARGA");

        combo_merk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_merkActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_man);
        rb_man.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rb_man.setText("MANUAL");
        rb_man.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_manActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_sprt);
        rb_sprt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rb_sprt.setText("SPORT");
        rb_sprt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_sprtActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_mtc);
        rb_mtc.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rb_mtc.setText("MATIC");
        rb_mtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_mtcActionPerformed(evt);
            }
        });

        tHarga.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_man)
                                .addGap(26, 26, 26)
                                .addComponent(rb_sprt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(rb_mtc))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(combo_merk, 0, 255, Short.MAX_VALUE)
                                    .addComponent(tHarga)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(combo_merk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb_man)
                    .addComponent(rb_sprt)
                    .addComponent(rb_mtc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(15, 15, 15))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("PEMBAYARAN");

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("HARGA MOTOR");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("DISKON");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("TOTAL BAYAR");

        tDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDiskonActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jLabel11.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tDiskon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addComponent(tTotbay, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(199, 199, 199)))
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tTotbay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        tNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNamaKeyTyped(evt);
            }
        });

        combo_byr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_byrActionPerformed(evt);
            }
        });

        btn_hitung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_hitung.setText("HITUNG");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        area.setEditable(false);
        area.setColumns(20);
        area.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        area.setRows(5);
        area.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        area.setFocusable(false);
        jScrollPane1.setViewportView(area);

        button_print.setText("CETAK BUKTI");
        button_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_printActionPerformed(evt);
            }
        });

        button_logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button_logout.setText("LOG OUT");
        button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(182, 182, 182)
                        .addComponent(button_logout))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_print)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(tNama))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(combo_byr, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(button_logout))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(combo_byr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_print, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    ProsesTugas mtr = new ProsesTugas();
    private void rb_sprtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_sprtActionPerformed
        // TODO add your handling code here:
        ProsesTugas prosesTugas = new ProsesTugas();
        prosesTugas.setMerk(combo_merk.getSelectedItem().toString());
        prosesTugas.setSeleksiMerk();
        tHarga.setText(decimalFormat.format(prosesTugas.getSport()));

    }//GEN-LAST:event_rb_sprtActionPerformed

    private void combo_merkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_merkActionPerformed
        // TODO add your handling code here:
        mtr.setMerk(combo_merk.getSelectedItem().toString());
        mtr.setSeleksiMerk();
        mtr.getManual();
        mtr.getMatic();
        mtr.getSport();
    }//GEN-LAST:event_combo_merkActionPerformed

    private void tDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDiskonActionPerformed

    private void rb_manActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_manActionPerformed
        // TODO add your handling code here:
        ProsesTugas prosesTugas = new ProsesTugas();
        prosesTugas.setMerk(combo_merk.getSelectedItem().toString());
        prosesTugas.setSeleksiMerk();
        tHarga.setText(decimalFormat.format(prosesTugas.getManual()));

    }//GEN-LAST:event_rb_manActionPerformed

    private void rb_mtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_mtcActionPerformed
        // TODO add your handling code here:
        ProsesTugas prosesTugas = new ProsesTugas();
        prosesTugas.setMerk(combo_merk.getSelectedItem().toString());
        prosesTugas.setSeleksiMerk();
        tHarga.setText(decimalFormat.format(prosesTugas.getMatic()));

    }//GEN-LAST:event_rb_mtcActionPerformed

    private void combo_byrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_byrActionPerformed
        // TODO add your handling code here:
        mtr.setBayar(combo_byr.getSelectedItem().toString());
        mtr.setSeleksiBayar();
        tDiskon.setText(String.valueOf(mtr.diskon));
    }//GEN-LAST:event_combo_byrActionPerformed

    private String formatDiscount(int discount, boolean isPercentage) {
        if (isPercentage) {
            return discount + "%";
        } else {
            DecimalFormat decimalFormat = new DecimalFormat("Rp.###,###,###");
            return decimalFormat.format(discount);
        }
    }


    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        ProsesTugas prosesTugas = new ProsesTugas();
        prosesTugas.setMerk(combo_merk.getSelectedItem().toString());
        prosesTugas.setSeleksiMerk();
        prosesTugas.setBayar(combo_byr.getSelectedItem().toString());
        prosesTugas.setSeleksiBayar();
        int harga = 0;
        if (rb_man.isSelected()) {
            harga = prosesTugas.getManual();
        } else if (rb_sprt.isSelected()) {
            harga = prosesTugas.getSport();
        } else if (rb_mtc.isSelected()) {
            harga = prosesTugas.getMatic();
        }
        int diskon = prosesTugas.diskon;
        int totalBayar = harga - (harga * diskon / 100);

        DecimalFormat decimalFormat = new DecimalFormat("Rp###,###,###");
        String totalBayarFormatted = decimalFormat.format(totalBayar);

        tHarga.setText(decimalFormat.format(harga));
        tDiskon.setText(String.valueOf(diskon));
        tTotbay.setText(totalBayarFormatted);

        // Determine if the discount is a percentage or an amount
        boolean isPercentageDiscount = true; // Set your logic here to determine the discount format

        // Display the receipt in the text area
        area.setText("****************************************************\n");
        area.append("*                            Receipt System                       *\n");
        area.append("****************************************************\n\n");

        Date obj = new Date();
        String date = obj.toString();

        area.append(date + "\n\n");
        area.append("Nama Pembeli\t\t: " + tNama.getText() + "\n");
        area.append("Merk Motor\t\t: " + combo_merk.getSelectedItem().toString() + "\n");
        if (rb_man.isSelected()) {
            area.append("Jenis Motor\t\t: Manual\n");
        } else if (rb_sprt.isSelected()) {
            area.append("Jenis Motor\t\t: Sport\n");
        } else if (rb_mtc.isSelected()) {
            area.append("Jenis Motor\t\t: Matic\n");
        }

        area.append("Harga\t\t: " + decimalFormat.format(harga) + "\n");
        area.append("Metode Pembayaran\t: " + combo_byr.getSelectedItem().toString() + "\n");
        area.append("Diskon\t\t: " + (isPercentageDiscount ? diskon + "%" : decimalFormat.format(diskon)) + "\n");
        area.append("Total Pembayaran\t: " + totalBayarFormatted + "\n");
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        tNama.setText("");
        combo_merk.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        combo_byr.setSelectedIndex(0);
        tHarga.setText("");
        tDiskon.setText("");
        tTotbay.setText("");
        area.setText("");

        // Set isResultDisplayed to false
        isResultDisplayed = false;

    }//GEN-LAST:event_btn_clearActionPerformed

    private void button_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_printActionPerformed
        // TODO add your handling code here:
        try {
            area.print();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_button_printActionPerformed

    private void button_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutActionPerformed
        // TODO add your handling code here:
        // Dispose the main application window
        dispose();

        // Display logout successful prompt
        JOptionPane.showMessageDialog(null, "Logout Successful");

        // Create and display the login page
        Penjualan_Motor_Java loginPage = new Penjualan_Motor_Java();
        loginPage.setVisible(true);
    }//GEN-LAST:event_button_logoutActionPerformed

    private void tNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNamaKeyTyped
        // TODO add your handling code here:
        aktif();
    }//GEN-LAST:event_tNamaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasAkhirPBO.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasAkhirPBO.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasAkhirPBO.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasAkhirPBO.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TugasAkhirPBO().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_hitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_logout;
    private javax.swing.JButton button_print;
    private javax.swing.JComboBox<String> combo_byr;
    private javax.swing.JComboBox<String> combo_merk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_man;
    private javax.swing.JRadioButton rb_mtc;
    private javax.swing.JRadioButton rb_sprt;
    private javax.swing.JTextField tDiskon;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tTotbay;
    // End of variables declaration//GEN-END:variables
}
